### ISSUE TITLE
Bad branch name on docker compose

### ISSUE THREAD

**Issue by miceno** [artefactual/atom#931] opened 2019-07-23 14:14 UTC
When building docker images and composing them, the stated branch is `qa/2.5.x`, while the name of the default branch is `qa/2.6.x`.

**Comment by jraddaoui** [comment] 2019-08-01 12:43
Hi @miceno,

Again, thanks for the report and pull request!

This should be fixed after 9fa52d2. We're testing it internally in `qa/2.6.x` before adding it to `stable/2.5.x` too.

**Comment by jraddaoui** [comment] 2019-08-01 12:57
Closing as duplicate of https://github.com/artefactual/atom/issues/901.

**Closed as completed by jraddaoui** 2019-08-01 12:57 UTC
