### ISSUE TITLE
Problem: Google Analytics not collecting data with arDominionB5Plugin enabled

### ISSUE THREAD

**Issue by edugovi** [artefactual/atom#1608] opened 2023-06-14 10:25 UTC
### Current Behavior

**Steps to reproduce the behavior**
1. Log into AtoM as an administrator
2. Navigate to 'Admin > Themes'
3. Enable arDominionB5Plugin
4. Save and log out
5. Log into AtoM server
6. Edit file 'config/app.yml', adding a tracking code
7. Save, clear cache and restart php7.4-fpm service
8. Google Analytics is not collecting data after 48 hours

### Expected Behavior

Google Analytics is able to collect data.

### Possible Solution

Copying the file '_footer.php' from apps/qubit/templates/ to plugins/arDominionB5Plugin/templates/:

`sudo --user=www-data cp -i /usr/share/nginx/atom/apps/qubit/templates/_footer.php /usr/share/nginx/atom/plugins/arDominionB5Plugin/templates/.`

### Version used

AtoM 2.7.1

### Operating System and version

Ubuntu 20.04

### Default installation culture

ca

### PHP version

PHP 7.4

**Comment by Mbtj** [comment] 2023-06-20 17:52
Hi Eduard!

Thanks for the feedback!
This issue behaviour seems to match up with the one we fixed in 2.7.2, so we believe updating AtoM should fix this.

Closing this issue as this seems like a duplicate of [ref #13658](https://projects.artefactual.com/issues/13658), [#1580](https://github.com/artefactual/atom/pull/1580), but please do let us know if the issue still persists after the update, and we'll reopen it.

**Closed as completed by Mbtj** 2023-06-20 17:52 UTC
Labels: Type: bug
