### ISSUE TITLE
"Identify" XML response is not correctly escaped

### ISSUE THREAD

**Issue by paulcee** [artefactual/atom#803] opened 2018-12-06 17:13 UTC
In the response to an "Identify" request, ampersands may not be correctly escaped. For example:
https://catalogue.millsarchive.org/index.php/;oai?verb=Identify&
(The XML may not render correctly in your browser because of this very issue! Use "View Source".)

The response contains the text:
&lt;repositoryName&gt;Images & Documents&lt;/repositoryName&gt;
This does not appear to be valid XML. The ampersand sign & should be escaped as &amp;amp;

**Comment by fiver-watson** [comment] 2018-12-07 21:40
Hi @paulcee , thanks for this report. I have reproduced this issue locally, and filed a bug ticket for it in our issue tracker, here: 

* https://projects.artefactual.com/issues/12622

I've also added it to an internal list of community-reported bugs for consideration in our next public release. That doesn't guarantee we'll be able to address it however - if your institution is interested in using support tickets to prioritize a fix for this immediately, feel free to send me an email: dan [at] artefactual [dot] com. 

In the meantime, I'm going to close this GitHub issue, since we don't really use GitHub for issue tracking with AtoM. Thank you again for the report!

**Closed as completed by fiver-watson** 2018-12-07 21:40 UTC

**Comment by fiver-watson** [comment] 2019-01-02 22:16
Hi @paulcee just thought you'd like to know that one of our developers managed to tackle this bug over the break! It was a 1 line change :) 

See: https://github.com/artefactual/atom/pull/806/files

We'll include the fix in the 2.5 release. Thanks again for the report!
