### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by guillaumesoucy94** [artefactual/atom#1618] opened 2023-06-23 01:23 UTC
### Current Behavior

**Steps to reproduce the behavior**
1. Go to 'site_domain.tld'
2. It display an error
3. This is the error:
![Screenshot at 2023-06-22 21-17-09](https://github.com/artefactual/atom/assets/22561876/b6408e80-a373-48e6-9d7d-188937993a4a)
4. I'd follow this guide: https://www.accesstomemory.org/en/docs/2.8/admin-manual/installation/ubuntu/#installation-ubuntu

### Expected Behavior

The new deployment display something else than an 500 Internal Server Error. 

### Context and Notes

I'd use Ubuntu 22.04. Should I use 20.04 as suggested in guide? Same thing for PHP. Using 7.4 in place of 8.1?

After running `php symfony tools:install` and filled up informations, the terminal returns:

`[PHP Error] Return type of ConditionBase::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [line 49 of /mnt/disk/zawack.org/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/tasks/system/condition/ConditionBase.php]
[PHP Error] Return type of ConditionEnumeration::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [line 176 of /mnt/disk/zawack.org/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/tasks/system/condition/ConditionBase.php]
[PHP Error] Return type of ConditionEnumeration::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [line 184 of /mnt/disk/zawack.org/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/tasks/system/condition/ConditionBase.php]
[PHP Error] Return type of ConditionEnumeration::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [line 188 of /mnt/disk/zawack.org/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/tasks/system/condition/ConditionBase.php]
[PHP Error] Return type of ConditionEnumeration::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [line 172 of /mnt/disk/zawack.org/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/tasks/system/condition/ConditionBase.php]
[PHP Error] Return type of ConditionEnumeration::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice [line 192 of /mnt/disk/zawack.org/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/tasks/system/condition/ConditionBase.php]`

### Operating System and version

Ubuntu 22.04

### Default installation culture

en

### PHP version

PHP 8.1

### Contact details

guillaume.soucy@zawack.ca

**Comment by guillaumesoucy94** [comment] 2023-06-23 01:25
The used version is AtoM 2.7

Thank-you

**Comment by fiver-watson** [comment] 2023-06-23 12:19
Hi @guillaumesoucy94, 

This is not a bug with the application but an installation issue, and therefore I will be closing this issue shortly. 

At this time, AtoM does not support PHP 8.1, and has not been tested on Ubuntu 22.04. There are breaking changes in PHP8 that are likely impacting your installation, and it's also possible that many of the PHP extensions that AtoM requires behave differently with v8. 

To install AtoM 2.7.2, the latest stable version, please follow ALL instructions listed in this installation guide, as this is what our team tests prior to release:

* https://www.accesstomemory.org/docs/2.7/admin-manual/installation/ubuntu/

While we have tried to make our documentation as clear as possible, it still assumes that the user has basic familiarity with the unix command-line, and with the installation and maintenance of production-ready web based applications.

If you have general issues about the installation process, you can try posting them in the AtoM User Forum, here: 

* https://groups.google.com/g/ica-atom-users

Keep in mind that this is a free community-driven forum - Artefactual cannot offer detailed ongoing assistance or support. If you are interested in paid support, we do offer a number of AtoM services as well, including hosting, remote technical maintenance, training, and more. See: 

* https://www.artefactual.com/services/

Finally, we do have plans to update AtoM's support of both PHP and Ubuntu to the latest versions - for the current upcoming roadmap, see: 

* https://groups.google.com/g/ica-atom-users/c/uShs0qcwpGY/m/RlfFYRGOAgAJ

Hopefully, if you restart your installation process and use the correct version of Ubuntu and PHP for the [2.7.2 release](https://wiki.accesstomemory.org/Releases/Release_announcements/Release_2.7.2), you should be successful in your next attempt. Best of luck!

**Closed as not planned** 2023-06-23 12:19 UTC
Labels: Type: bug, Status: invalid
