### ISSUE TITLE
Problem: Update with csv file where records with same title and similar ids leads to mysql recursive error

### ISSUE THREAD

**Issue by jtgorman** [artefactual/atom#1785] opened 2024-03-27 19:09 UTC
### Current Behavior

One record gets updated, pointing to itself, then we get a recursion error. Visiting the record page leads to a 500 error and another recursion in the logs.

Row 111: Matching description found, updating in place; row (id: 24260, culture: en, legacyId: ALA-a-7895)...;  
Row 112: Matching description found, updating in place; row (id: 24260, culture: en, legacyId: ALA-d-3243)...;  
 
[wrapped: SQLSTATE[HY000]: General error: 3636 Recursive query aborted after 1001 iterations. Try increasing @@cte_max_recursion_depth to a larger value.] 

Dump of record 

mysql> select * from information_object where id = 24260\G 

*************************** 1. row *************************** 

id: 24260 
identifier: 22/14/10 
oai_local_identifier: 3340 
level_of_description_id: 299 
collection_type_id: NULL 
repository_id: 454 
parent_id: 24260 
description_status_id: NULL 
description_detail_id: NULL 
description_identifier: NULL 
source_standard: NULL 
display_standard_id: NULL 
lft: 6574 
rgt: 6575 
source_culture: en 

We believe the error  causing the 500 is related trying to display this broken record and related to some of the logic at 
[atom/lib/QubitFlatfileImport.class.php at qa/2.x · artefactual/atom (github.com)](https://github.com/artefactual/atom/blob/qa/2.x/lib/QubitFlatfileImport.class.php)
Line 1991 - private function setInformationObjectByFields()

 and the sql query generated like..
 ```
SELECT object.CLASS_NAME, object.CREATED_AT, object.UPDATED_AT, object.ID, object.SERIAL_NUMBER, information_object.ID, information_object.IDENTIFIER, information_object.OAI_LOCAL_IDENTIFIER, information_object.LEVEL_OF_DESCRIPTION_ID, information_object.COLLECTION_TYPE_ID, information_object.REPOSITORY_ID, information_object.PARENT_ID, information_object.DESCRIPTION_STATUS_ID, information_object.DESCRIPTION_DETAIL_ID, information_object.DESCRIPTION_IDENTIFIER, information_object.SOURCE_STANDARD, information_object.DISPLAY_STANDARD_ID, information_object.LFT, information_object.RGT, information_object.SOURCE_CULTURE FROM `object` CROSS JOIN `information_object` RIGHT JOIN (
        WITH RECURSIVE aas AS
        (
          SELECT tb1.id, tb1.parent_id, 1 as lev
          FROM information_object tb1
          WHERE tb1.id=24260
          UNION ALL
          SELECT tb2.id, tb2.parent_id, aas.lev + 1
          FROM information_object tb2
          JOIN aas ON aas.parent_id=tb2.id
        )
        SELECT id, lev FROM aas
      ) cte ON (information_object.ID=cte.id) WHERE information_object.ID=object.ID ORDER BY lev DESC
```

**Steps to reproduce the behavior**
1. Have a csv file where there’s two layers of records, both with the same title, but ids differ by punctuation characters (22-14-10 and 22/14/10). 
```
legacyId,parentId,qubitParentSlug,accessionNumber,identifier,title,levelOfDescription,extentAndMedium,repository,archivalHistory,acquisition,scopeAndContent,appraisal,accruals,arrangement,accessConditions,reproductionConditions,language,script,languageNote,physicalCharacteristics,findingAids,locationOfOriginals,locationOfCopies,relatedUnitsOfDescription,publicationNote,digitalObjectPath,digitalObjectURI,generalNote,subjectAccessPoints,placeAccessPoints,nameAccessPoints,genreAccessPoints,descriptionIdentifier,institutionIdentifier,rules,descriptionStatus,levelOfDetail,revisionHistory,languageOfDescription,scriptOfDescription,sources,archivistNote,publicationStatus,physicalObjectName,physicalObjectLocation,physicalObjectType,alternativeIdentifiers,alternativeIdentifierLabels,eventDates,eventTypes,eventStartDates,eventEndDates,eventActors,eventActorHistories,culture
ALA-a-7895,,,,22-14-10,"CLS Newsletter",,,"American Library Association Archives",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Published,,,,,,,,,,,,en
ALA-d-3243,ALA-a-7895,,,22/14/10,"CLS Newsletter",Part,PDF,"American Library Association Archives",,,"Digital copies of the CLS Newsletter, published semi-annually, contains reports from the chair, conference news and reports, short articles, and announcements about section meetings and programs.",,,,,"College Libraries Section of the Association of College and Research Libraries",,,,,,,,,,,https://alair.ala.org/handle/11213/14127,,,,,,,,,,,,,,,,Published,,,,3243,"Archon ID",NULL|NULL|1987-2020,"Creation|Creation|Inclusive Dates",,,"College Libraries Section|Association of College and Research Libraries (ACRL)",,en
```
2. Run an "update" csv import via the web interface OR I think the following command line (based on some log info I was given) `php '/usr/share/nginx/atom/symfony' 'csv:import' --index --update="match-and-update" --quiet --user-
id="450" --source-name='atom-csv-digitalcontent_ala_c.csv'`

### Expected Behavior

I'd expect two records to be created, with one record (ALA-d-3243) pointing to the parent record (ALA-a-7895).

Or at least a warning that the record couldn't be imported due to resulting recusion

### Possible Solution

Best case scenario - have a way to specify roundtrip in the web interface which I think might make the code handle this. Or at least if the id and parent_id are the same don't 

### Version used

AtoM 2.8

**Comment by jtgorman** [comment] 2024-03-27 21:54
Not sure if this should be a separate issue - we also ran into some confusing behavior when experimenting with handling this problem.  I had expected the --roundtrip flag to help with the issue where the lookup was probably finding the wrong record. It seemed to help when running an update, but when just doing a normal csv output, it seemed to break things as entries in the keymap table weren't made. 

From the documentation this might be intentional, but it's confusing to me. Maybe there needs to be something like --legacy-id separate from --runtrip ?  Maybe I'm not understanding the point of roundtrip or why it seems to have different affects when doing an import vs import with an --upgrade flag.

Some of this comes from taking the command that was in the dump from the web interface import, so that could be part of my confusion.

**Comment by fiver-watson** [comment] 2024-03-28 13:56
Hi @jtgorman, thanks for this report! I will let the team of AtoM Maintainers review the bug report in greater detail, try to reproduce it themselves, and respond on their own terms. 

In the meantime, I just wanted to provide a bit more context for some of the questions and confusions you have. 

In short: the CSV update import functionality was implemented on a project with not enough budget or time, and focusing on a use case that is not how most people want to actually use it. It really needs an overhaul. If you are curious to know more, you can read about it in a couple previous forum posts, here: 

* https://groups.google.com/g/ica-atom-users/c/HMoN4tEuJ10/m/n4e1gqftBQAJ
* Similar info, but another version: https://groups.google.com/g/ica-atom-users/c/bCWYFIkLCRs/m/7QTPfLnQAQAJ

A couple clarifications: 

>  I had expected the --roundtrip flag to help with the issue where the lookup was probably finding the wrong record. It seemed to help when running an update, but when just doing a normal csv output, it seemed to break things as entries in the keymap table weren't made.

We can perhaps make it clearer in the documentation, but the `--roundtrip` option is **only** intended to be used in conjunction with the `--update` option. It changes the matching criteria from sourcename and legacyId to an exact match on the legacyId value against the internal `object_id` of a record in AtoM's database - a match that can only happen a) if the record you are trying to update already exists in AtoM (otherwise it will not have an `object_id` value), and b) if it is an attempt to _update_ an existing record (otherwise you don't need matching criteria, you just import as new). 

> Have a csv file where there’s two layers of records, both with the same title, but ids differ by punctuation characters (22-14-10 and 22/14/10)

Just to clarify: you said you used the `--update` option. Meaning - these records already exist in your AtoM installation, and you are attempting to update their metadata, correct? You are not trying to create new records? I only ask because you say: 

> I'd expect two records to be created, with one record (ALA-d-3243) pointing to the parent record (ALA-a-7895).

When I tried importing your example CSV via the user interface as **new** records, it worked as expected without errors - I got a parent record with no level of description and an identifier of `22-14-10`, and a child Part-level record with an identifier value of `22/14/10`. AtoM had no issue keeping the different identifiers separate. 

I then edited the CSV, changing the extent and scope and content statements on both, and even the title on one of them, and re-imported it using the "match and update" option, and it still worked without any errors. Matches were found for each (meaning matching on the filename as --source-name and matching on the same legacyID values worked), and my title, extent statements and scope and content statements were all updated. So, the identifiers do not appear to be the issue here. 

I am wondering if perhaps the real issue you are encountering is caused by previous imports terminating incompletely, leaving some data corruption in place that is then affecting your ability to perform future update imports? We have some methods to check for this, though I strongly recommend you make a database backup before pursuing any of them, and proceed at your own risk. 

First, there are some SQL queries in our Troubleshooting documentation that can check for common types of data corruption in descriptions - there are also some fixes suggested for the most common findings. See: 

* https://www.accesstomemory.org/docs/latest/admin-manual/maintenance/troubleshooting/#dealing-with-data-corruption

Meanwhile, one of our developers created a script that will automate these checks, which you can download, save on your AtoM server, and run locally if you wish - see this forum thread: 

* https://groups.google.com/g/ica-atom-users/c/mWPG763-seQ/m/ecTLNBT7AwAJ

Finally, a version of that script will be turned into a command-line task for the next major AtoM release. If you are an adept command-line and git user, you could try adding it as a patch to your local installation, as the changes seem to be self-contained in one file, and it does not look like it requires schema migrations - see: 

* https://github.com/artefactual/atom/commit/1154198c8f6c6a75e043149069884fa9572a6a82

Finally: 

> Best case scenario - have a way to specify roundtrip in the web interface which I think might make the code handle this. Or at least if the id and parent_id are the same don't

Personally, I strongly agree with you that we should add roundtrip support to the user interface in a future release. The CLI `--roundtrip` option was an experimental attempt to address the shortcomings of the original import matching logic design, to simplify it for how most people actually want to use the update functionality (i.e. exporting their own records, updating them in the CSV, and then importing that as a metadata update to the existing records). I hope to see this in a future release - though it is not currently scheduled. 

However, it's also important that we clarify the intended use of this, and what it will and won't help fix for you. Roundtripping implies that you exported the records from AToM FIRST - because when you do so, AtoM will put the internal database object_id value IN the export CSV's legacyId column. Then, when you use the roundtrip option, it ignores all other criteria and just looks for an exact match there. Since MySQL requires each record to have a unique ID value, there should never be conflicts. 

However, if you are not exporting the records first and using the exported legacyID values, then this also adds to the issue. We can review the existing documentation and see how we can further clarify this. 

In the meantime, please let us know: 

1. If I have misunderstood how to reproduce this bug report - if so, I will happily re-test!
2. If you find any data corruption - and if the tools help you to resolve it, whether this changes the outcome of your import attempts

**Comment by jtgorman** [comment] 2024-03-28 16:16
It's entirely possible that there's some data stuck in the database. I'll try to take some time next week to investigate a bit more and post some more information.

## Background

For some more background- a coworker of mine has been experimenting with different ways to migrate from our Archon data.  She's out of the office at the moment, but I had a chance to meet with her recently and I wanted to file this while it was still fresh in my mind ;). I've got more command-line and software debugging experience, so I started poking around too.

We think we have a process working now, pretty much what you described. (I've got a summary in a section below).

## More info on replicating 

Looking at my notes, there's one other complication. It sounds like they added the parent records in one pass, but then were trying to add various children records of different types that pointed to the parent. So we might have both a record for a physical item and a digital scan for an item attached to a parent record in Archon.

The import of the second layer of records initially complained of the parent not being included in the file, so they added some stub records where the ids matched up.  Now, most likely they've also been changing filenames, so I suspect the "source-name" was also changing.

Next week I'm hoping to recreate with a true minimal set, with made up records that follow similar patterns.

## Working approach 
We experimented with a few different approaches, so we've verified we can likely get it working using the command line and not using the update flag, similar to what you said. Basically, load in the records, keep the same source-name, don't use stub records. Do it either in passes or make sure the ordering is right. 

Basically when I started experimenting with using the command-line instead of the web interface I...

  1. Started with a command-line from the output of the web interface update run
  2. tried adding the roundtrip flag (came from seeing it in some of the code related to the recursion error)
  3. Had issues because the records didn't exist (does the web interface do multiple passes? Seems like from what I saw of the output it created records that didn't match anything )
  4. Tried removing the upgrade, because I figured we add in the records without an uprade then.  Wasn't importing (because of the keymap)
  5.  dropped the roundtrip, verified cli worked either by making sure we went from top to bottom of hiearchy in the same file, or in mutliple files with the same source-name and no stub records.

I still worry there's edge cases though that could end up with the recursive error happening though, especially if someone tries to use the web interface to correct or import some data.

## Why we used the upgrade options

My coworker started with trying to use the web interface for csv import. It seems like that creates records if they weren't present and also might be doing further validations that the command-line doesn't by default? 

I think my coworker was also assumed that a more exact match was being used throughout the process. She stated validation looks for an id in the same file, but without the roundtrip the code for update-and-match looks for metadata and has fuzzy match on id?  Probably works in 99.9% to a lot of 9s of cases.  But in some of our edge cases the "match" might be same title, but an id different punctation. Seems like maybe two records get created, and another pass goes to "update" and pulls the wrong record as the top match?

It would be nice to have an option for updates to be able to use a less fuzzy match, since we do have unique ids for all of this. I know most of the staff would prefer to use a web interface for this process. (Although, since it's only going to be a one-time thing if we decide to go with AtoM, I'm not too worried about it ;) 

## roundtrip without upgrade flag

This might sound silly, but the documentation is already pretty long. (Don't want to complain too much...too many projects don't have enough).  It would probably be more user-friendly to either have the command-line die quickly and complain when --roundtrip is used without an upgrade flag or the code that alters behaviors for stuff like the keymap checks both upgrade flag and roundtrip are present.


Whew, sorry for the long response, but like I mentioned earlier, want to do some of this while it's all fresh in my head.

Ps - happy to do a zoom or some other meeting at some point ;).

**Comment by fiver-watson** [comment] 2024-03-28 20:14
Hi @jtgorman ! 

Thanks for the additional context. I hope to provide you with some further links and clarifications that might help your migration succeed. 

> For some more background- a coworker of mine has been experimenting with different ways to migrate from our Archon data.

We have done several Archon migrations in the past, and there are some significant differences in the basic entity model between Archon and AtoM that are worth understanding in advance - particularly around how authority records are created and work in AtoM, AtoM's phsyiscal storage module, and the difference between the intellectual arrangement of your archival collections (e.g. fonds or record group or collection > series > subsseries > file > item) and the physical arrangement  (i.e. shelf > box > folder > document, etc) that is different than Archon. 

I would suggest checking out some of our previous forum posts on the matter - you can turn up a number just by searching "Archon migration": 

* https://groups.google.com/g/ica-atom-users/search?q=archon%20migration

I also have put together a slide deck on AtoM migrations for our AtoM training camps - trying to summarize some of the lessons I have learned after overseeing migration projects for many years. See: 

* https://www.slideshare.net/accesstomemory/atom-data-migrations

Now, if you are working with CSVs as your primary migration format (which is better than XML in my opinion), it is important to understand the AtoM import CSV templates well. I know the documentation is a lot and can therefore be overwhelming, so I have also tried to summarize some of the key information in this slide deck (also used in training camps): 

* https://www.slideshare.net/accesstomemory/csv-import-in-atom

I hope that these resources might help a bit! 

>  It sounds like they added the parent records in one pass, but then were trying to add various children records of different types that pointed to the parent.

You might have figured this out already, but allow me to clarify the parent child relationship management in AtoM CSV imports. 

There are 2 main ways of managing this - the quick summary is: 

1. Use the `parentId` column with the legacyId value of the target parent, when the parent is included in the SAME csv - i.e. you are creating both parent and child in the same import
2. Use the `qubitParentSlug` column with the slug (i.e. permalink, i.e. unique part of the URL) of the target parent as the value when you want to import a new child record from your CSV to a parent record that ALREADY exists in AtoM

In general, we recommend all records be given a legacyId during an import, but it's not actually mandatory - UNLESS you are including hierarchical relationships in the CSV. In that case, you NEED an ID value to refer to, to add to the parentId column. 

A CSV can include the use of both parentId values and qubitParentSlug values, but not in the same _row_ -  if a single row contains both, AtoM will ignore the parentId value and use the slug value instead,

So for option 1: 

* Ensure every unique record row in your CSV has a unique legacyId value
* Ensure that any parent record appears in a row ABOVE the child - AtoM's import progresses row by rows, so if a row references a parent ID but that target parent hasn't been created yet, you wil get errors

See: https://www.accesstomemory.org/docs/latest/user-manual/import-export/csv-import/#legacyid-and-parentid

For option 2: 

* The slug must point to an existing record in AtoM
* Slugs in AtoM must be unique, so there shouldn't be any collisions

See: https://www.accesstomemory.org/docs/latest/user-manual/import-export/csv-import/#qubitparentslug

Most importantly: 

On their own, NEITHER OF THESE options are considered updates to existing records. You may be appending a child to an existing record, which seems like an update to that record... but it's metadata is unchanged. You are still creating a NEW child record, as well as a new relationship between the existing record and the child. 

So, it sounds like your colleague should have used the qubiParentSlug column on a new import, to add more new child records, rather than trying to use the update methods and the IDs. 

> Had issues because the records didn't exist (does the web interface do multiple passes? Seems like from what I saw of the output it created records that didn't match anything )

Thanks to this mention I did actually notice a bug in our new Bootstrap 5 templates that may have impacted your experience configuring the import via the interface. By default when performing match-and-update imports, if no match is found, then AtoM will treat the row as a new record, and create it as such. Obviously this could lead to a lot of accidental duplicate records being created if the match logic is not working as expected (and admittedly, AtoM's matching logic is not great by default), so we do have an option to skip unmatched records - `--skip-unmatched` on the CLI task. 

This actually is an option in the UI too.... only it seems it is missing from the newer Bootstrap 5 templates! I have filed a bug for this here: 

* https://github.com/artefactual/atom/issues/1789

Hopefully the AtoM maintainers can address this in an upcoming release. 

Otherwise, AFAIK the UI is simply using the Gearman job scheduler and atom-worker to kick off the import asynchronously, and in the background it is using the same CSV import CLI task. So there shouldn't be differences in default behavior. 

> My coworker started with trying to use the web interface for csv import. It seems like that creates records if they weren't present and also might be doing further validations that the command-line doesn't by default?

AtoM 2.8 DOES now have a CSV validation option - which I highly recommend that you use! You can use it separately (either via the UI or as a separate CLI task), but what you might have encountered is that an Administrator can also turn on a setting so that the validator is automatically run BEFORE any web import. On the CLI, you have to choose to run the separate validation task. See: 

* CSV validation in general: https://www.accesstomemory.org/docs/latest/user-manual/import-export/csv-validation/
* the CSV validation CLI task: https://www.accesstomemory.org/docs/latest/admin-manual/maintenance/cli-import-export/#validate-csv-files-via-the-command-line-before-import
* the CSV validation on import settings: https://www.accesstomemory.org/docs/latest/user-manual/administer/settings/#csv-validator-settings


> I think my coworker was also assumed that a more exact match was being used throughout the process. She stated validation looks for an id in the same file, but without the roundtrip the code for update-and-match looks for metadata and has fuzzy match on id? Probably works in 99.9% to a lot of 9s of cases. But in some of our edge cases the "match" might be same title, but an id different punctation. Seems like maybe two records get created, and another pass goes to "update" and pulls the wrong record as the top match?

I think that the forum posts I provided previously might clear this up a bit more but, if you are actually trying to update the metadata of existing records (and not just append new child records), then: 

* By default, AtoM will look for a match in the keymap table against legacyId and sourcename. 
* If it doesn't find a match on that, it will fall back and check to see if there is an EXACT match on key metadata elements for a given row - title, identifier, and repository
* Failing that, it will import the record as new - UNLESS you use the skip-unmatched option, in which case the row will be skipped. 

This is clearly not a great design, since previous legacyId values are not visible anywhere in AtoM, and if you don't use the exact same ones AND the same source-name (so.... filename if using the UI, since as you've noted there is no option to set that in the web UI right now and it defaults to filefame), then it's really hard to get a match. 

Additionally, the fallback logic means that if you are TRYING to update the title or identifier then your matches will fail, since they will no longer match! 

This is exactly why we added the --roundtrip option on the command-line - as a way to provide less fuzzy matching logic. 

* On an export from AtoM, the legacyId column is NOT populated with whatever legacyId you might have used when importing. Instead, AtoM will populate this with the unique object ID assigned by MySQL - an absolutely unique value in the database. 
* When importing with the `--roundtrip` option then, AtoM will look in the CSV's legacyId column and look for an EXACT match against the internal object IDs - if an exact match is not found, then it is skipped or imported as new. 

Changes I hope to see in the future include: 

* Adding a --roundtrip option to the web user interface
* Making the CLI task fail if --roundtrip is used, but --update is not

There are more issues, but those are the ones germain to your situation for now! 

> This might sound silly, but the documentation is already pretty long. (Don't want to complain too much...too many projects don't have enough). It would probably be more user-friendly to either have the command-line die quickly and complain when --roundtrip is used without an upgrade flag or the code that alters behaviors for stuff like the keymap checks both upgrade flag and roundtrip are present.

Definitely agree. Ideally we can simplify the whole process, and thereby reduce the docs. In the meantime, I hope that these explanations, links, and additional materials like the slides will help curate all this information a bit, and help you to succeed! 

Good luck! 

For now, I am going to close this issue as we have not yet reproduced the bug as reported. If you need further guidance on your migration, make a post in the AtoM User Forum and I will do my best to help!

**Closed as completed by fiver-watson** 2024-03-28 20:14 UTC
Labels: Type: bug
