### ISSUE TITLE
Only supports format YYYY-MM-DD for start/end dates

### ISSUE THREAD

**Issue by martinmaillard** [artefactual/atom#759] opened 2018-07-27 15:30 UTC
Hello,

The help text for the start and end date fields of an archival description says that acceptable date formats are YYYYMMDD, YYYY-MM-DD, YYYY-MM and YYYY, but the last two don't seem to be handled properly. If I enter a date without a valid month and day, it gets recorded as "0".

I'm using Atom 2.4 (I just tested 2.5 and the problem is still here)

Thanks

**Comment by jmtiong** [comment] 2018-07-31 04:34
Greetings!

I have attempted to replicate the bug on the demo site version 2.4.0, the format `YYYY` gets detected by the site and convert into `YYYY-MM-DD` that showed results.

The format `YYYY-MM` on the other hand threw error indicating the format is wrong and it is properly handled.

May I know where did you see the help text that indicates the format as I could not find it.
![image](https://user-images.githubusercontent.com/16659123/43437706-088ab404-94bd-11e8-9532-493e50f4b6e0.png)

This gif shows that the `YYYY` format did pass. 

![YYYY format](https://user-images.githubusercontent.com/16659123/43437808-8a7ac6e8-94bd-11e8-9987-9351677649b8.gif)

As for the `YYYY-MM` format, since the format does not qualifies for the search, it threw an error back to the user.

![YYYY-MM format](https://user-images.githubusercontent.com/16659123/43439025-a62ef296-94c3-11e8-8603-bca7e10ffd88.gif)

Here’s the test script that I use in Uilicious for `YYYY` format.

```javascript
// Go to the bug reporting website
I.goTo("https://demo.accesstomemory.org/informationobject/browse");

// Set the variables for start and end date
var startYear = 1992;
var endYear   = 1993;

// Open the advance options
I.click("Advanced search options");

// Fill in the information
I.fill("Start", startYear);
I.fill("End", endYear);
I.pressEnter();

// Search the result
I.see("Reset");
I.click("Search");

// Perform assertion
I.see("Showing 29 results");

// View the dates changed and results
I.scrollBy(0, 600);
```
And the script for the `YYYY-MM` format.
```javascript
// Go to the bug reporting website
I.goTo("https://demo.accesstomemory.org/informationobject/browse");

// Set the variables for start and end date

// Open the advance options
I.click("Advanced search options");

// Fill in the information
I.fill("Start", "1992-07");
I.fill("End", "1993-07");
I.pressEnter();

// Search the result
I.see("Reset");
I.click("Search");

// Perform assertion
I.see("does not match the date format");
```

**Comment by martinmaillard** [comment] 2018-07-31 07:01
Sorry, I should have provided more details.

The issue is not related to the search engine, but to the Archival description creation form. Here is the relevant section of the form, with the help text displayed on the left:

<img width="1095" alt="screen shot 2018-07-31 at 08 53 37" src="https://user-images.githubusercontent.com/1334124/43442816-66a9d614-949f-11e8-8ebe-8f71a9725e1a.png">

If I enter either "2018" or "2018-05" and save, the value is changed to "0" ("0000-00-00" in MySQL).

It's happening on two different installs, one of which is a fresh Docker install (as described on https://www.accesstomemory.org/en/docs/2.5/dev-manual/env/compose/#dev-env-compose).

The weird thing is that I just tried to replicate it on the demo instance that you mentioned and it seems to work properly... maybe it's a MySQL configuration issue?

**Comment by jraddaoui** [comment] 2018-08-01 06:57
Hi @martinmaillard and @jmtiong, thanks for reporting this!

---

@martinmaillard, as you supposed, this looks to be a MySQL configuration issue. The AtoM database has to accept zero dates and zeros in dates to allow the behavior you're expecting. To achieve that, the 'sql-mode' system variable must not include `NO_ZERO_IN_DATE` nor `NO_ZERO_DATE`:

https://dev.mysql.com/doc/refman/5.6/en/using-date.html

The Docker compose environment is currently running MySQL with both options included in the 'sql-mode':

https://github.com/artefactual/atom/blob/qa%2F2.5.x/docker/etc/mysql/conf.d/sql_mode.cnf#L3

I'll change it in there. Again, thanks for letting us know!

---

@jmtiong, first, I didn't knew about Uilicious, that looks amazing for things like this!

About the issue you're seeing in the advanced search date range, this looks to be the intended behavior:

https://github.com/artefactual/atom/blob/qa/2.5.x/js/dominion.js#L731-L741

@fiver-watson, allowing `YYYY-MM` dates in the adv. search form will require a little more work than only year dates, to properly get the last day of the month, but it could be done in around 4 hours. Is that something you'd like to see?

**Comment by jraddaoui** [comment] 2018-08-01 08:45
@martinmaillard, the issue should be fixed in the Docker compose environment using the latest changes from the stable/2.4.x or qa/2.5.x branches.

@fiver-watson, I'm not sure if we mention this in the installation docs, I'd appreciate if you could take care of that alongside the other issue ;)

**Comment by fiver-watson** [comment] 2018-08-01 19:21
Hi @jraddaoui  and @martinmaillard, 

RE: no YYYY-MM format support in the Advanced date search: this is documented functionality as described here: 

* https://www.accesstomemory.org/docs/2.4/user-manual/access-content/advanced-search/#using-the-date-range-search-filter

Note that it should still return YYYY-MM results that fall within the target range. 

Radda, if it is possible to add support for YYYY-MM that could be a nice add, but unless someone wants to sponsor the work, it's not currently a priority - we have a backlog of client work and other unsponsored bugs with a higher priority!

**Comment by jraddaoui** [comment] 2018-08-01 19:54
Great, thanks @fiver-watson!

@martinmaillard, if you want to give it a try to the 'sql-mode' changes in the Docker compose environment before closing the issue, that would be great.

**Comment by martinmaillard** [comment] 2018-08-02 07:07
@jraddaoui Thank you for your quick reaction. I just tested the docker-compose environment and it works properly now.

**Closed as completed** 2018-08-09 07:23 UTC
